### ISSUE TITLE
Issue with mocha when migrating to v1.0.1

### ISSUE THREAD

**Issue by ftomassetti** [snabbdom/snabbdom#748]
Hi, I am getting this error from mocha:

```
rror [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/federico/repos/webeditkit/node_modules/snabbdom/build/package/init.js
require() of ES modules is not supported.
require() of /Users/federico/repos/webeditkit/node_modules/snabbdom/build/package/init.js from /Users/federico/repos/webeditkit/src/facade.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename init.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/federico/repos/webeditkit/node_modules/snabbdom/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/federico/repos/webeditkit/src/facade.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/federico/repos/webeditkit/src/internal.ts:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/federico/repos/webeditkit/test/communication.spec.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/federico/repos/webeditkit/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.exports.requireOrImport (/Users/federico/repos/webeditkit/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/Users/federico/repos/webeditkit/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/Users/federico/repos/webeditkit/node_modules/mocha/lib/mocha.js:421:19)
    at singleRun (/Users/federico/repos/webeditkit/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/Users/federico/repos/webeditkit/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/Users/federico/repos/webeditkit/node_modules/mocha/lib/cli/run.js:366:11)
    at /Users/federico/repos/webeditkit/node_modules/yargs/lib/command.js:241:49
```

I am using snabbdom in tests I run on Node.JS. All code is in typescript. I import snabbdom like this:

```
import { init } from 'snabbdom/build/package/init';
import {classModule} from 'snabbdom/build/package/modules/class';
import {propsModule} from 'snabbdom/build/package/modules/props';
import {styleModule} from 'snabbdom/build/package/modules/style';
import {eventListenersModule} from 'snabbdom/build/package/modules/eventlisteners';
import {datasetModule} from 'snabbdom/build/package/modules/dataset';
```

(I know about the workaround for specifying paths in the package.json but it seems to lead to more problems than solutions and it is not solving this issue).

Do you have any idea about this error? Does someone have faced something similar?

I have been tried to update snabbdom for a while but I keep failing :(

**Comment by mightyiam** [comment]
What's likely occurring is that in your TypeScript project, your tests code is transpiled from ES modules into CommonJS modules. While snabbdom is not transpiled in such a way. It remains ES modules. Untouched. What needs to happen in your project is that snabbdom must be transpiled into CommonJS for you to be able to `require` it in CommonJS. Another idea is a runtime ES modules loader for Node.js, such as https://www.npmjs.com/package/esm. That actually sounds easier.

**Comment by jvanbruegge** [comment]
Fixed in v3
